version: '3.3'
services:
  nginx:
    build: ./nginx
    volumes:
      - ./web_app/static_root:/code/static_root
      - ./web_app/media:/code/media
    ports:
      - "5555:80"
    depends_on:
      - web

  web:
    build: ./web_app
    env_file: ./my.env
    command: /code/run.sh
    volumes:
      - ./web_app:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
  cache:
    image: memcached
    ports:
      - "11211:11211"
    entrypoint:
      - memcached
      - -m 64

  db:
    image: postgres
    env_file: ./my.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5454:5432"

volumes:
  postgres_data: