# Generated by Django 3.0.5 on 2020-05-03 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0003_auto_20200425_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author',
                                    to='news.Author'),
        ),
    ]
