# Generated by Django 3.0.6 on 2020-05-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_author_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='avatar',
            field=models.ImageField(default='images/noava.png', upload_to='images/avatars'),
        ),
    ]
