# Generated by Django 3.0.6 on 2020-05-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_comment_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.TextField(),
        ),
    ]
